apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: lms-config-server
  name: lms-config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lms-config-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: lms-config-server
    spec:
      containers:
        - image: apaspxp/lms-config-server:latest
          name: lms-config-server
          resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: lms-config-server
  name: lms-config-server
spec:
  ports:
    - name: 5555-5555
      port: 5555
      protocol: TCP
      targetPort: 5555
      nodePort: 30000
  selector:
    app: lms-config-server
  type: NodePort
status:
  loadBalancer: {}
